/* Vendored from PAS design-kit (00_personal_agent_system/design-kit/typescript/src/{tokens,cockpitProfiles}.ts).
 * Do not edit token VALUES by hand — sync from design-kit. Vendored so the
 * stand-alone stock-intel repo builds without the vault sibling on a fresh clone.
 * Source of truth: design-kit tokens.ts is generated by
 * Harness/scripts/generate_design_tokens.py. Re-sync when tokens change. */

export const pasTokens = {
  color: {
    bg: "#f7f8fa",
    surface: "#ffffff",
    surfaceAlt: "#eef2f6",
    line: "#d9dee5",
    text: "#17191c",
    textMuted: "#606873",
    accent: "#8ecae6",
    accentSoft: "#e8f5fb",
    successAccent: "#9ad7b5",
    risk: "#b42318",
    warn: "#b54708",
    ok: "#087443",
    info: "#175cd3",
  },
  typography: {
    font: 'Pretendard, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    bodyLetterSpacing: "-0.02em",
    bodyLineHeight: "1.6",
  },
  radius: { sm: "4px", md: "8px" },
  spacing: { xs: "4px", sm: "8px", md: "16px", lg: "24px", xl: "32px" },
  meta: {
    iconSet: "Coolicons",
    colorRule: "neutral base + one accent + point-only status color",
  },
} as const;

export type PasTokens = typeof pasTokens;

// design-kit dashboard-cockpit-kit.md required common tabs (exact labels).
export const commonCockpitTabs = ["요약", "진행현황", "주의 필요", "근거", "다음 행동"] as const;
