"""Curated v1 seed data for local dashboard rendering."""

from __future__ import annotations

from dashboard.models import DashboardInput, parse_dashboard_input


SAMPLE_DASHBOARD = {
    "as_of": "2026-05-29",
    "price_time": "2026-05-29 00:15 UTC",
    "regime": {
        "verdict": "conditional",
        "risk_appetite": "risk-on",
        "rates": "stable",
        "dollar": "stable",
        "volatility": "low",
        "notes": [
            "AI 인프라 수요는 살아 있지만 반도체 주가는 조정을 받을 수 있습니다.",
            "전력·아날로그 반도체는 AI 인프라의 2차 병목이 될 수 있습니다.",
        ],
    },
    "market_indicators": [
        {
            "symbol": "SPY",
            "name": "S&P 500 ETF",
            "group": "미국 대형주",
            "price": 682.55,
            "day_change_pct": 0.39,
            "read": "위험자산 선호 유지. 시장 전체가 무너지는 국면은 아님.",
        },
        {
            "symbol": "QQQ",
            "name": "Nasdaq 100 ETF",
            "group": "성장주",
            "price": 642.65,
            "day_change_pct": 0.83,
            "read": "성장주 선호가 시장 대비 강함. AI 후보의 가격 부담도 같이 점검 필요.",
        },
        {
            "symbol": "SMH",
            "name": "Semiconductor ETF",
            "group": "반도체",
            "price": 599.83,
            "day_change_pct": 0.76,
            "read": "반도체 강세 지속. 신규 진입은 후보별 가격 매력 확인이 필요.",
        },
        {
            "symbol": "XLK",
            "name": "Technology Select Sector",
            "group": "기술주",
            "price": 346.84,
            "day_change_pct": 0.88,
            "read": "기술주가 시장을 주도. 단기 과열과 실적 상향을 분리해야 함.",
        },
        {
            "symbol": "XLI",
            "name": "Industrial Select Sector",
            "group": "산업재",
            "price": 169.10,
            "day_change_pct": 0.39,
            "read": "전력·데이터센터 인프라 후보와 연결되는 후방 섹터.",
        },
    ],
    "lenses": [
        {
            "id": "ai_agent_compute",
            "kind": "thesis",
            "name": "AI 에이전트 컴퓨팅",
            "conviction": "high",
            "direction": "improving",
            "weights": {
                "growth": 0.35,
                "revision": 0.25,
                "valuation": 0.15,
                "momentum": 0.15,
                "quality": 0.10,
            },
            "risks": ["빅테크 투자 피로"],
        },
        {
            "id": "ai_power_bottleneck",
            "kind": "thesis",
            "name": "AI 전력 병목",
            "conviction": "high",
            "direction": "improving",
            "weights": {
                "growth": 0.25,
                "revision": 0.25,
                "valuation": 0.20,
                "quality": 0.15,
                "momentum": 0.15,
            },
            "risks": ["늦은 사이클의 가격 인상"],
        },
        {
            "id": "low_per_revision",
            "kind": "factor",
            "name": "가치평가 + 이익상향",
            "conviction": "medium",
            "direction": "improving",
            "weights": {
                "valuation": 0.40,
                "revision": 0.30,
                "quality": 0.15,
                "growth": 0.10,
                "momentum": 0.05,
            },
            "risks": ["싸 보이는 함정"],
        },
        {
            "id": "semiconductors",
            "kind": "sector",
            "name": "반도체",
            "conviction": "medium",
            "direction": "stable",
            "weights": {
                "growth": 0.25,
                "revision": 0.20,
                "valuation": 0.25,
                "momentum": 0.20,
                "quality": 0.10,
            },
            "risks": ["밸류에이션 부담"],
        },
        {
            "id": "power_analog",
            "kind": "sector",
            "name": "전력·아날로그 반도체",
            "conviction": "medium",
            "direction": "improving",
            "weights": {
                "valuation": 0.25,
                "quality": 0.20,
                "growth": 0.20,
                "revision": 0.20,
                "momentum": 0.15,
            },
            "risks": ["자동차·산업재 사이클 부담"],
        },
        {
            "id": "risk_on_liquidity",
            "kind": "macro",
            "name": "위험자산 선호",
            "conviction": "medium",
            "direction": "stable",
            "weights": {
                "momentum": 0.35,
                "growth": 0.25,
                "revision": 0.20,
                "quality": 0.10,
                "valuation": 0.10,
            },
            "risks": ["유동성 반전"],
        },
    ],
    "stocks": [
        {
            "ticker": "ON",
            "company": "ON Semiconductor",
            "sector": "Power Semiconductors",
            "lens_ids": ["ai_power_bottleneck", "power_analog"],
            "thesis": "AI 서버 전력 공급망이 타이트해질수록 전력반도체 쪽으로 수혜가 번질 수 있는 후보.",
            "metrics": {
                "valuation": 74,
                "quality": 58,
                "growth": 66,
                "revision": 70,
                "momentum": 60,
            },
            "evidence": ["AI 데이터센터 사업이 강하게 성장했다는 회사 측 언급"],
            "bull_case": [
                "GPU/HBM 중심 랠리 이후 전력반도체 병목으로 관심이 이동할 때 민감도가 큼.",
                "저평가·이익상향 관점이 함께 붙으면 단순 경기민감주가 아니라 재평가 후보가 됨.",
            ],
            "bear_case": [
                "자동차·EV·SiC 사이클 둔화가 AI 데이터센터 성장 신호를 희석할 수 있음.",
                "가격 인상 뉴스가 실제 마진 개선이 아니라 원가 전가에 그치면 매력도가 약해짐.",
            ],
            "gaps": ["다음 공시 후 정상화 이익 기준 가치평가 재확인 필요"],
            "next_action": "다음 실적에서 AI 데이터센터 매출, 매출총이익률, 재고 흐름을 먼저 확인.",
            "price": 123.77,
            "day_change_pct": 1.39,
            "pe": 91.0,
        },
        {
            "ticker": "TXN",
            "company": "Texas Instruments",
            "sector": "Analog Semiconductors",
            "lens_ids": ["ai_power_bottleneck", "power_analog"],
            "thesis": "가장 넓은 아날로그·전력관리 노출을 가진 품질주. AI 전력 수요가 산업재 회복과 겹치면 방어적인 2차 수혜가 가능.",
            "metrics": {
                "valuation": 48,
                "quality": 78,
                "growth": 58,
                "revision": 62,
                "momentum": 68,
            },
            "evidence": ["산업재와 데이터센터 수요 언급이 전력관리 노출을 뒷받침"],
            "bull_case": [
                "PMIC, 전력관리, 산업재 수요를 넓게 받는 구조라 단일 제품 리스크가 낮음.",
                "데이터센터 전력 체인이 넓어질수록 범용 아날로그 부품 수요가 같이 살아날 수 있음.",
            ],
            "bear_case": [
                "이미 품질 프리미엄을 받는 종목이라 가치평가 재평가 여지가 제한될 수 있음.",
                "산업재 회복이 지연되면 AI 관련 노출만으로 전체 성장률을 끌어올리기 어려움.",
            ],
            "gaps": [],
            "next_action": "동종 기업 대비 예상 PER와 잉여현금흐름 수익률을 비교해 추격 여부보다 조정 대기 가격을 잡기.",
            "price": 315.95,
            "day_change_pct": -0.11,
            "pe": 54.0,
        },
        {
            "ticker": "ADI",
            "company": "Analog Devices",
            "sector": "Analog Semiconductors",
            "lens_ids": ["ai_power_bottleneck", "power_analog"],
            "thesis": "전력밀도와 혼합신호 품질에 베팅하는 후보. AI 인프라가 '더 많은 연산'에서 '더 조밀한 전력 전달'로 이동할 때 유리.",
            "metrics": {
                "valuation": 42,
                "quality": 82,
                "growth": 62,
                "revision": 64,
                "momentum": 70,
            },
            "evidence": ["Empower 인수로 전력밀도 포지션 강화"],
            "bull_case": [
                "고품질 아날로그 사업에 AI 전력밀도 이야기가 붙으면서 장기 투자 이야기가 선명함.",
                "전력 전달, 센싱, 혼합신호 포트폴리오가 데이터센터 외 산업재 회복과도 연결됨.",
            ],
            "bear_case": [
                "품질주 프리미엄이 높아 실적이 좋아도 기대치가 먼저 앞설 수 있음.",
                "인수 효과가 매출·마진으로 확인되기 전에는 이야기만 앞설 위험이 있음.",
            ],
            "gaps": [],
            "next_action": "Empower 인수 이후 데이터센터 전력밀도 관련 수주·제품 언급이 반복되는지 추적.",
            "price": 419.01,
            "day_change_pct": 0.59,
            "pe": 62.0,
        },
        {
            "ticker": "NVDA",
            "company": "NVIDIA",
            "sector": "Accelerated Compute",
            "lens_ids": ["ai_agent_compute", "semiconductors", "risk_on_liquidity", "low_per_revision"],
            "thesis": "AI 에이전트 확산이 추론 사용량을 구조적으로 키운다는 핵심 기준점. 다만 투자 가설이 맞는 것과 주가가 싼 것은 분리해야 함.",
            "metrics": {
                "valuation": 30,
                "quality": 92,
                "growth": 95,
                "revision": 88,
                "momentum": 90,
            },
            "evidence": ["데이터센터 매출이 AI 인프라 수요의 기준 신호 역할"],
            "bull_case": [
                "에이전트는 계획·검색·검증·재시도를 반복하므로 일반 챗봇보다 추론 사용량이 커질 수 있음.",
                "AI 인프라 투자가 이어지는 한 데이터센터 매출이 전체 공급망의 기준 신호 역할을 함.",
            ],
            "bear_case": [
                "시장 기대치가 이미 2027년 수요와 옵션 가치를 크게 반영했을 수 있음.",
                "빅테크 설비투자 피로가 나오면 실수요가 있어도 가치평가부터 흔들릴 수 있음.",
            ],
            "gaps": ["주가가 이미 큰 옵션 가치를 반영했을 가능성"],
            "next_action": "추격 후보가 아니라 설비투자 가이던스와 추론 매출화를 확인하는 기준 종목으로 둠.",
            "price": 212.30,
            "day_change_pct": 1.58,
            "pe": 32.6,
        },
        {
            "ticker": "DELL",
            "company": "Dell Technologies",
            "sector": "AI Servers",
            "lens_ids": ["ai_agent_compute", "semiconductors", "low_per_revision"],
            "thesis": "AI 서버 매출이 실제 주문과 출하로 연결되는지 확인하기 좋은 후방 인프라 후보.",
            "metrics": {
                "valuation": 58,
                "quality": 62,
                "growth": 76,
                "revision": 68,
                "momentum": 72,
            },
            "evidence": ["AI 서버 수요가 데이터센터 설비투자와 직접 연결"],
            "bull_case": [
                "GPU 공급망 수요가 서버 출하와 기업 인프라 투자로 이어질 때 수혜가 명확함.",
                "반도체보다 가치평가 부담이 낮아 보이면 AI 인프라 2차 후보가 될 수 있음.",
            ],
            "bear_case": [
                "서버 사업은 마진이 반도체보다 얇아 매출 성장만으로 주가가 계속 오르기 어려움.",
                "AI 서버 매출 전망이 이미 주가에 반영됐는지 확인 필요.",
            ],
            "gaps": ["AI 서버 수주잔고와 마진 기여도 확인 필요"],
            "next_action": "다음 실적에서 AI 서버 매출 전망, 마진, 주문잔고가 같이 개선되는지 확인.",
            "price": 317.05,
            "day_change_pct": 3.65,
            "pe": 42.3,
        },
        {
            "ticker": "WDC",
            "company": "Western Digital",
            "sector": "Storage & Memory",
            "lens_ids": ["semiconductors", "low_per_revision"],
            "thesis": "AI 데이터센터 확산이 저장장치와 메모리 사이클까지 끌어올릴 때 상대적으로 가치평가 부담이 낮은 후보.",
            "metrics": {
                "valuation": 66,
                "quality": 55,
                "growth": 70,
                "revision": 64,
                "momentum": 70,
            },
            "evidence": ["데이터센터 저장 수요와 메모리 업사이클 관점이 동시에 연결"],
            "bull_case": [
                "AI 인프라가 GPU를 넘어 저장장치·메모리 수요로 번질 때 후행 수혜 가능.",
                "대표 AI 반도체보다 PER 부담이 낮아 가치평가 재평가 후보가 될 수 있음.",
            ],
            "bear_case": [
                "메모리·스토리지는 사이클 피크에서 이익이 부풀어 싸 보일 수 있음.",
                "가격 상승이 재고 축적에 기반한 것인지 실수요에 기반한 것인지 확인 필요.",
            ],
            "gaps": ["정상화 이익과 메모리 가격 사이클 위치 확인 필요"],
            "next_action": "메모리 가격, 데이터센터 저장 수요, 이익 추정치 상향 여부를 함께 확인.",
            "price": 531.18,
            "day_change_pct": 0.10,
            "pe": 31.8,
        },
        {
            "ticker": "VRT",
            "company": "Vertiv",
            "sector": "Data Center Power & Cooling",
            "lens_ids": ["ai_power_bottleneck", "risk_on_liquidity"],
            "thesis": "AI 데이터센터가 전력·냉각 병목으로 이동할 때 직접적인 인프라 수혜를 받는 후보.",
            "metrics": {
                "valuation": 38,
                "quality": 70,
                "growth": 82,
                "revision": 74,
                "momentum": 88,
            },
            "evidence": ["데이터센터 전력·냉각 수요와 가장 직접적으로 연결되는 장비 후보"],
            "bull_case": [
                "GPU 랙 전력밀도가 올라갈수록 냉각·전력 장비 수요가 동반 확대될 수 있음.",
                "반도체가 비싸 보일 때 AI 인프라 후방 장비로 관심이 이동할 수 있음.",
            ],
            "bear_case": [
                "가격 모멘텀이 이미 강해 신규 진입은 조정 대기 원칙이 필요.",
                "데이터센터 발주 지연이나 전력망 병목이 매출 인식 속도를 늦출 수 있음.",
            ],
            "gaps": ["수주잔고와 데이터센터 매출 비중 최신 확인 필요"],
            "next_action": "실적발표에서 AI 데이터센터 수주잔고, 마진, 납기 관련 표현을 확인.",
            "price": 314.29,
            "day_change_pct": 2.53,
            "pe": 90.5,
        },
        {
            "ticker": "MPWR",
            "company": "Monolithic Power Systems",
            "sector": "Power Management",
            "lens_ids": ["ai_power_bottleneck", "power_analog"],
            "thesis": "고밀도 전력관리 반도체 후보. AI 서버 전력 공급 효율이 병목이 될수록 관심을 받을 수 있음.",
            "metrics": {
                "valuation": 36,
                "quality": 84,
                "growth": 74,
                "revision": 68,
                "momentum": 79,
            },
            "evidence": ["고성능 전력관리 부품이 AI 서버 전력 전달 문제와 연결"],
            "bull_case": [
                "AI 서버의 전력 안정성과 효율이 중요해질수록 고밀도 전력관리 수요가 커질 수 있음.",
                "품질과 성장성이 같이 보이는 전력관리 대표 후보.",
            ],
            "bear_case": [
                "높은 가치평가가 작은 실망에도 주가 변동을 키울 수 있음.",
                "고객 집중도와 경쟁 강도 확인이 필요.",
            ],
            "gaps": ["AI 서버 매출 기여도와 고객 집중도 확인 필요"],
            "next_action": "경쟁사 대비 매출 성장률, 매출총이익률, AI 서버 언급 빈도를 비교.",
            "price": 1399.54,
            "day_change_pct": 1.28,
            "pe": 84.8,
        },
    ],
}


def load_sample_dashboard_input() -> DashboardInput:
    return parse_dashboard_input(SAMPLE_DASHBOARD)
